feat(wsdl-meta): add soap and soap12 namespaces if WSDL contains both
DigDes/SoapCore pull request #1047
Opened 2024-03-29 15:11 UTC by Yozer

When a service has bindings with mixed soap11/soap12 versions the produced WSDL was correct but it every "soap11" element had extra namespace.
This PR adds soap namespace to the wsdl definition.

2024-05-28 13:31 UTC, andersjonsson requested changes
Unless I'm missing something there is a duplicate check in one of your if-statements.
Other than that it looks really good. Thanks!

2024-05-28 13:31 UTC, andersjonsson commented on src/SoapCore/Meta/MetaMessage.cs
> +			    _soapVersions.Contains(MessageVersion.Soap11WSAddressingAugust2004))
```suggestion
			if (_soapVersions.Contains(MessageVersion.Soap11) ||
			    _soapVersions.Contains(MessageVersion.Soap11WSAddressingAugust2004))
```

2024-05-30 16:22 UTC, Yozer commented
> Unless I'm missing something there is a duplicate check in one of your if-statements. Other than that it looks really good. Thanks!

Yep, that was a typo, thanks!

2024-05-31 09:40 UTC, andersjonsson approved these changes

2024-05-31 09:40 UTC, andersjonsson commented
Thanks!

2024-05-31 09:40 UTC, merged